llama-server \
-hf unsloth/gemma-4-12b-it-GGUF:UD-Q4_K_XL \
-ngl 99 \
--ctx-size $((128*1024)) \
--spec-type draft-mtp --spec-draft-n-max 4 \
-np 1 \
-fa on \
--mmap \
--mlock \
-t 6 \
--temp 1 --top-p 0.95 --top-k 64 \
--jinja \
--metrics \
--host 0.0.0.0 \
--reasoning on 
